---
title: "Acquire_data"
format: pdf
editor: visual
---

```{r}
#### Workspace setup ####
install.packages("opendatatoronto")
install.packages("knitr")

library(knitr)
library(janitor)
library(lubridate)
library(opendatatoronto)
library(tidyverse)
```

```{r}
library(opendatatoronto)
packages <- list_packages(limit = 10)
packages
#> # A tibble: 10 x 11
#>    title id    topics civic_issues publisher excerpt dataset_category
#>    <chr> <chr> <chr>  <chr>        <chr>     <chr>   <chr>           
#>  1 Cata… 473d… City … <NA>         Informat… Histor… Table           
#>  2 Lobb… 6a87… City … <NA>         Lobbyist… The Lo… Document        
#>  3 Addr… abed… Locat… Mobility     Informat… This d… Document        
#>  4 Prop… 1aca… Locat… Mobility     Informat… This d… Document        
#>  5 Buil… 108c… Devel… Affordable … Toronto … Provid… Document        
#>  6 Buil… 8219… Devel… <NA>         Toronto … Provid… Document        
#>  7 Muni… 5da2… City … Affordable … Municipa… This d… Document        
#>  8 Shor… fc41… Permi… Affordable … Municipa… This d… Table           
#>  9 Poll… 7bce… City … <NA>         City Cle… Polls … Table           
#> 10 Dail… 8a6e… City … Affordable … Shelter,… Daily … Table           
#> # … with 4 more variables: num_resources <int>, formats <chr>,
#> #   refresh_rate <chr>, last_refreshed <date>
```

```{r}
show_package("996cfe8d-fb35-40ce-b569-698d51fc683b")
#> # A tibble: 1 x 11
#>   title id    topics civic_issues publisher excerpt dataset_category
#>   <chr> <chr> <chr>  <chr>        <chr>     <chr>   <chr>           
#> 1 TTC … 996c… <NA>   <NA>         <NA>      <NA>    <NA>            
#> # … with 4 more variables: num_resources <int>, formats <chr>,
#> #   refresh_rate <chr>, last_refreshed <date>
```

```{r}
aa = list_package_resources("https://open.toronto.ca/dataset/sexual-health-clinic-locations-hours-and-services/")
#> # A tibble: 2 x 4
#>   name                               id                     format last_modified
#>   <chr>                              <chr>                  <chr>  <date>       
#> 1 sexual-health-clinic-locations-ho… e958dd45-9426-4298-ac… XLSX   2019-08-15   
#> 2 Sexual-health-clinic-locations-ho… 2edcc4a3-c095-4ce3-b0… XLSX   2019-08-15
aa
```



```{r}
#### Acquire ####
toronto_shelters <-
  # Each package is associated with a unique id  found in the "For 
  # Developers" tab of the relevant page from Open Data Toronto
  # https://open.toronto.ca/dataset/daily-shelter-overnight-service-occupancy-capacity/
  # Original package id
  list_package_resources("21c83b32-d5a8-4106-a54f-010dbe49f6f2") |>
  # Within that package, we are interested in the 2021 dataset
  # Selected package
  filter(name == 
    "daily-shelter-overnight-service-occupancy-capacity-2021.csv") |>
  # Having reduced the dataset to one row we can get the resource
  get_resource()

write_csv(
  x = toronto_shelters,
  file = "toronto_shelters.csv"
)

head(toronto_shelters)
```
